export const mocked_forecast = [
  {
    number: 1,
    name: 'This Afternoon',
    startTime: '2023-04-17T12:00:00-05:00',
    endTime: '2023-04-17T18:00:00-05:00',
    isDaytime: true,
    temperature: 71,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: null,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: 1.1111111111111112,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 33,
    },
    windSpeed: '10 mph',
    windDirection: 'S',
    icon: 'https://api.weather.gov/icons/land/day/skc?size=medium',
    shortForecast: 'Sunny',
    detailedForecast: 'Sunny, with a high near 71. South wind around 10 mph.',
  },
  {
    number: 2,
    name: 'Tonight',
    startTime: '2023-04-17T18:00:00-05:00',
    endTime: '2023-04-18T06:00:00-05:00',
    isDaytime: false,
    temperature: 43,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: null,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: 3.3333333333333335,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 73,
    },
    windSpeed: '5 to 15 mph',
    windDirection: 'E',
    icon: 'https://api.weather.gov/icons/land/night/few?size=medium',
    shortForecast: 'Mostly Clear',
    detailedForecast:
      'Mostly clear, with a low around 43. East wind 5 to 15 mph, with gusts as high as 20 mph.',
  },
  {
    number: 3,
    name: 'Tuesday',
    startTime: '2023-04-18T06:00:00-05:00',
    endTime: '2023-04-18T18:00:00-05:00',
    isDaytime: true,
    temperature: 79,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: null,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: 10.555555555555555,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 79,
    },
    windSpeed: '10 to 20 mph',
    windDirection: 'SE',
    icon: 'https://api.weather.gov/icons/land/day/few?size=medium',
    shortForecast: 'Sunny',
    detailedForecast:
      'Sunny, with a high near 79. Southeast wind 10 to 20 mph, with gusts as high as 25 mph.',
  },
  {
    number: 4,
    name: 'Tuesday Night',
    startTime: '2023-04-18T18:00:00-05:00',
    endTime: '2023-04-19T06:00:00-05:00',
    isDaytime: false,
    temperature: 60,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: 30,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: 13.333333333333334,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 84,
    },
    windSpeed: '20 mph',
    windDirection: 'S',
    icon: 'https://api.weather.gov/icons/land/night/tsra_hi,30?size=medium',
    shortForecast: 'Chance Showers And Thunderstorms',
    detailedForecast:
      'A chance of showers and thunderstorms between 7pm and 10pm, then a chance of showers and thunderstorms between 10pm and 1am, then a slight chance of showers and thunderstorms. Mostly cloudy, with a low around 60. South wind around 20 mph, with gusts as high as 35 mph. Chance of precipitation is 30%.',
  },
  {
    number: 5,
    name: 'Wednesday',
    startTime: '2023-04-19T06:00:00-05:00',
    endTime: '2023-04-19T18:00:00-05:00',
    isDaytime: true,
    temperature: 81,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: 20,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: 12.777777777777779,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 84,
    },
    windSpeed: '15 to 20 mph',
    windDirection: 'SW',
    icon: 'https://api.weather.gov/icons/land/day/tsra_hi,20?size=medium',
    shortForecast: 'Slight Chance Showers And Thunderstorms',
    detailedForecast:
      'A slight chance of showers and thunderstorms. Mostly sunny, with a high near 81. Southwest wind 15 to 20 mph, with gusts as high as 30 mph. Chance of precipitation is 20%.',
  },
  {
    number: 6,
    name: 'Wednesday Night',
    startTime: '2023-04-19T18:00:00-05:00',
    endTime: '2023-04-20T06:00:00-05:00',
    isDaytime: false,
    temperature: 47,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: 70,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: 8.333333333333334,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 71,
    },
    windSpeed: '15 to 25 mph',
    windDirection: 'NE',
    icon: 'https://api.weather.gov/icons/land/night/tsra_hi,50/tsra_hi,70?size=medium',
    shortForecast: 'Chance Showers And Thunderstorms',
    detailedForecast:
      'A chance of showers and thunderstorms before 1am, then showers and thunderstorms likely. Mostly cloudy, with a low around 47. Northeast wind 15 to 25 mph, with gusts as high as 35 mph. Chance of precipitation is 70%.',
  },
  {
    number: 7,
    name: 'Thursday',
    startTime: '2023-04-20T06:00:00-05:00',
    endTime: '2023-04-20T18:00:00-05:00',
    isDaytime: true,
    temperature: 66,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: 70,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: 5.555555555555555,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 74,
    },
    windSpeed: '15 to 25 mph',
    windDirection: 'NW',
    icon: 'https://api.weather.gov/icons/land/day/tsra_hi,70/tsra_hi,20?size=medium',
    shortForecast: 'Showers And Thunderstorms Likely',
    detailedForecast:
      'Showers and thunderstorms likely before 1pm. Mostly sunny, with a high near 66. Northwest wind 15 to 25 mph, with gusts as high as 40 mph. Chance of precipitation is 70%.',
  },
  {
    number: 8,
    name: 'Thursday Night',
    startTime: '2023-04-20T18:00:00-05:00',
    endTime: '2023-04-21T06:00:00-05:00',
    isDaytime: false,
    temperature: 39,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: 20,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: -1.1111111111111112,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 60,
    },
    windSpeed: '10 to 15 mph',
    windDirection: 'NW',
    icon: 'https://api.weather.gov/icons/land/night/sct/rain_showers,20?size=medium',
    shortForecast: 'Partly Cloudy then Slight Chance Rain Showers',
    detailedForecast:
      'A slight chance of rain showers after 1am. Partly cloudy, with a low around 39. Northwest wind 10 to 15 mph, with gusts as high as 25 mph. Chance of precipitation is 20%.',
  },
  {
    number: 9,
    name: 'Friday',
    startTime: '2023-04-21T06:00:00-05:00',
    endTime: '2023-04-21T18:00:00-05:00',
    isDaytime: true,
    temperature: 57,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: 20,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: -1.1111111111111112,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 62,
    },
    windSpeed: '15 to 25 mph',
    windDirection: 'NW',
    icon: 'https://api.weather.gov/icons/land/day/rain_showers,20?size=medium',
    shortForecast: 'Slight Chance Rain Showers',
    detailedForecast:
      'A slight chance of rain showers before 1pm. Partly sunny, with a high near 57. Northwest wind 15 to 25 mph, with gusts as high as 35 mph. Chance of precipitation is 20%.',
  },
  {
    number: 10,
    name: 'Friday Night',
    startTime: '2023-04-21T18:00:00-05:00',
    endTime: '2023-04-22T06:00:00-05:00',
    isDaytime: false,
    temperature: 31,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: 20,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: -3.888888888888889,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 66,
    },
    windSpeed: '15 to 20 mph',
    windDirection: 'NW',
    icon: 'https://api.weather.gov/icons/land/night/rain_showers,20?size=medium',
    shortForecast: 'Slight Chance Rain Showers',
    detailedForecast:
      'A slight chance of rain showers after 7pm. Partly cloudy, with a low around 31. Chance of precipitation is 20%.',
  },
  {
    number: 11,
    name: 'Saturday',
    startTime: '2023-04-22T06:00:00-05:00',
    endTime: '2023-04-22T18:00:00-05:00',
    isDaytime: true,
    temperature: 52,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: 20,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: -4.444444444444445,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 66,
    },
    windSpeed: '15 to 20 mph',
    windDirection: 'NW',
    icon: 'https://api.weather.gov/icons/land/day/rain_showers,20/sct?size=medium',
    shortForecast: 'Slight Chance Rain Showers then Mostly Sunny',
    detailedForecast:
      'A slight chance of rain showers before 7am. Mostly sunny, with a high near 52. Chance of precipitation is 20%.',
  },
  {
    number: 12,
    name: 'Saturday Night',
    startTime: '2023-04-22T18:00:00-05:00',
    endTime: '2023-04-23T06:00:00-05:00',
    isDaytime: false,
    temperature: 29,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: null,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: -5.555555555555555,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 75,
    },
    windSpeed: '10 to 20 mph',
    windDirection: 'NW',
    icon: 'https://api.weather.gov/icons/land/night/sct?size=medium',
    shortForecast: 'Partly Cloudy',
    detailedForecast: 'Partly cloudy, with a low around 29.',
  },
  {
    number: 13,
    name: 'Sunday',
    startTime: '2023-04-23T06:00:00-05:00',
    endTime: '2023-04-23T18:00:00-05:00',
    isDaytime: true,
    temperature: 59,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: null,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: -4.444444444444445,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 75,
    },
    windSpeed: '10 to 15 mph',
    windDirection: 'NW',
    icon: 'https://api.weather.gov/icons/land/day/sct?size=medium',
    shortForecast: 'Mostly Sunny',
    detailedForecast: 'Mostly sunny, with a high near 59.',
  },
  {
    number: 14,
    name: 'Sunday Night',
    startTime: '2023-04-23T18:00:00-05:00',
    endTime: '2023-04-24T06:00:00-05:00',
    isDaytime: false,
    temperature: 38,
    temperatureUnit: 'F',
    temperatureTrend: null,
    probabilityOfPrecipitation: {
      unitCode: 'wmoUnit:percent',
      value: 20,
    },
    dewpoint: {
      unitCode: 'wmoUnit:degC',
      value: -2.2222222222222223,
    },
    relativeHumidity: {
      unitCode: 'wmoUnit:percent',
      value: 64,
    },
    windSpeed: '10 mph',
    windDirection: 'S',
    icon: 'https://api.weather.gov/icons/land/night/sct/rain_showers,20?size=medium',
    shortForecast: 'Partly Cloudy then Slight Chance Rain Showers',
    detailedForecast:
      'A slight chance of rain showers after 1am. Partly cloudy, with a low around 38. Chance of precipitation is 20%.',
  },
];
